spring:
  application:
    name: 08-SB-MiniProject-Profiles-PropertiesFiles
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: Manager
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
